version: "3.8"
services: 
  node-app:
    container_name: node-app-development-container
    build: 
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src:ro
    environment:
      - MY_ENV=Development
